CREATE TABLE IF NOT EXISTS users (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL,
  email         TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS products (
  id              INTEGER PRIMARY KEY,
  name            TEXT NOT NULL,
  brand           TEXT,
  category        TEXT,
  price           REAL NOT NULL,
  compareatprice  REAL,
  rating          REAL,
  stock           INTEGER DEFAULT 0,
  description     TEXT,
  image           TEXT
);

CREATE TABLE IF NOT EXISTS orders (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number      TEXT NOT NULL UNIQUE,
  tracking_number   TEXT,
  user_id           INTEGER REFERENCES users(id),
  items_json        TEXT NOT NULL,
  shipping_json     TEXT NOT NULL,
  subtotal          REAL NOT NULL,
  shipping_fee      REAL NOT NULL,
  total             REAL NOT NULL,
  currency          TEXT NOT NULL DEFAULT 'usd',
  payment_provider  TEXT NOT NULL DEFAULT 'stripe',
  payment_method    TEXT DEFAULT 'stripe',
  payment_intent_id TEXT,
  bakong_md5        TEXT,
  bakong_qr_string  TEXT,
  bakong_tran_id    TEXT,
  payment_status    TEXT NOT NULL DEFAULT 'pending',
  payment_expires_at TIMESTAMPTZ,
  paid_at           TIMESTAMPTZ,
  status_index      INTEGER NOT NULL DEFAULT 1,
  is_recovery       INTEGER DEFAULT 0,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_orders_bakong_md5 ON orders(bakong_md5);
