-- Reset / Drop tables in dependency order
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS user_devices CASCADE;
DROP TABLE IF EXISTS auth_events CASCADE;
DROP TABLE IF EXISTS search_events CASCADE;
DROP TABLE IF EXISTS search_cache CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users (
  id                        TEXT PRIMARY KEY DEFAULT gen_random_uuid(),
  name                      TEXT,
  display_name              TEXT,
  email                     TEXT NOT NULL UNIQUE,
  password_hash             TEXT NOT NULL,
  avatar_url                TEXT,
  bio                       TEXT,
  is_public                 BOOLEAN DEFAULT true,
  email_verified            BOOLEAN DEFAULT false,
  legacy_auth               BOOLEAN DEFAULT false,
  supabase_uid              TEXT,
  welcomed_at               TIMESTAMPTZ,
  deleted_at                TIMESTAMPTZ,
  deletion_scheduled_for    TIMESTAMPTZ,
  created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS products (
  id              INTEGER PRIMARY KEY,
  name            TEXT NOT NULL,
  brand           TEXT,
  category        TEXT,
  price           REAL NOT NULL,
  compareatprice  REAL,
  rating          REAL,
  stock           INTEGER DEFAULT 0,
  description     TEXT,
  image           TEXT
);

CREATE TABLE IF NOT EXISTS orders (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number      TEXT NOT NULL UNIQUE,
  tracking_number   TEXT,
  user_id           TEXT REFERENCES users(id),
  items_json        TEXT NOT NULL,
  shipping_json     TEXT NOT NULL,
  subtotal          REAL NOT NULL,
  shipping_fee      REAL NOT NULL,
  total             REAL NOT NULL,
  currency          TEXT NOT NULL DEFAULT 'usd',
  payment_provider  TEXT NOT NULL DEFAULT 'stripe',
  payment_method    TEXT DEFAULT 'stripe',
  payment_intent_id TEXT,
  bakong_md5        TEXT,
  bakong_qr_string  TEXT,
  bakong_tran_id    TEXT,
  payment_status    TEXT NOT NULL DEFAULT 'pending',
  payment_expires_at TIMESTAMPTZ,
  paid_at           TIMESTAMPTZ,
  status_index      INTEGER NOT NULL DEFAULT 1,
  is_recovery       INTEGER DEFAULT 0,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_orders_bakong_md5 ON orders(bakong_md5);

CREATE TABLE IF NOT EXISTS sessions (
  id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                   TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  refresh_token             TEXT NOT NULL,
  access_token_expires_at   TIMESTAMPTZ NOT NULL,
  last_used_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_devices (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_hash   TEXT NOT NULL,
  user_agent    TEXT,
  ip            TEXT,
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_user_device UNIQUE (user_id, device_hash)
);

CREATE TABLE IF NOT EXISTS auth_events (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       TEXT REFERENCES users(id) ON DELETE SET NULL,
  event_type    TEXT NOT NULL,
  ip            TEXT,
  user_agent    TEXT,
  metadata      JSONB,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS search_cache (
  query         TEXT NOT NULL,
  type          TEXT NOT NULL DEFAULT '',
  sort          TEXT NOT NULL DEFAULT '',
  response_json TEXT NOT NULL,
  expires_at    TIMESTAMPTZ NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (query, type, sort)
);

CREATE TABLE IF NOT EXISTS search_events (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       TEXT REFERENCES users(id) ON DELETE SET NULL,
  query         TEXT NOT NULL,
  type          TEXT,
  result_count  INTEGER DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
